### PR TITLE
HW1

### PR DESCRIPTION
**Pull request by Antines**

### CODE REVIEW

**Comment by rinnifox** [comment]
Hi Raphael! 

A few comments to fix: 

1) Please create `.gitignore` file and add `*Zone.Identifier` files there, so that they are not messing up your repo. 

2) Reset indeed did the job since revert commit has not been pushed. It's ok since it has not been explicitly stated in homework to push this commit, but just remember we have discussed at the lecture that `reset` is not a good solution if your work on a real project, so use it with caution. Please add in your report how the same thing could be also achieved with `revert` command according to what I've suggested in course chat :) 

Otherwise it's ok!
Hope you will be able to accomplish these minor corrections by tomorrow evening.

**Comment by Antines** [comment]
Didn't add in report about the git revert way to resolve the conflict, as I solved it in a different way, here is the explanation:
Either it could have been solved by **git revert <hash of previous revert>** to back testing branch changes
(2nd file change) into HW1 and remerge it without conflict

**Comment by rinnifox** [comment]
1. Good! Can you also `git rm` current zone identifier files in your HW1 branch please?
2. Alright. Just note that this second hash revert should be done in HW1 and then this would be enough without any subsequent re-merges :)

**Comment by Antines** [comment]
Done! Thank you so much for your feedback!)

**Pull request merged**
